; Devstral-Small-2-24B-Instruct (Q8_K_XL - 28GB)
; Balanced code/general model.

version = 1

[devstral-small-24b]
model = /home/jaegle/models/Devstral-Small-2-24B-Instruct/Devstral-Small-2-24B-Instruct-2512-UD-Q8_K_XL.gguf
c = 262144
b = 2048
ub = 2048
t = 8
ngl = 999
flash-attn = on
jinja = true
load-on-startup = true
